import { BaseEntity } from '../../shared/entities/base.entity';

export class User extends BaseEntity {
    private constructor(
        id: string,
        public readonly username: string,
        private hashedPassword: string,
        public readonly fullName: string,
        public readonly mail: string,
        public readonly createdAt: Date,
    ) {
        super(id);
    }

    static create(
        username: string,
        fullName: string,
        mail: string,
        passwordHash: string,
    ): User {
        const now = new Date();
        return new User(
            '', // ID will be generated by Prisma
            username,
            passwordHash,
            fullName,
            mail,
            now,
        );
    }

    static reconstitute(
        id: string,
        username: string,
        hashedPassword: string,
        fullName: string,
        mail: string,
        createdAt: Date,
    ): User {
        return new User(
            id,
            username,
            hashedPassword,
            fullName,
            mail,
            createdAt,
        );
    }
    
      getPasswordHash(): string {
        return this.hashedPassword;
      }
    
      updatePassword(newPasswordHash: string): void {
        this.hashedPassword = newPasswordHash;
      }

}